SET DEFINE OFF
SET SERVEROUTPUT ON
SET PAGESIZE 100
SET LINESIZE 180

BEGIN EXECUTE IMMEDIATE 'DROP TABLE NX_TICKET_COMMENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NX_TICKETS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NX_TECHNICIANS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NX_USERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE NX_COMMENT_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE NX_TECH_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE NX_USER_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE NX_TICKET_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE NX_USERS (
    USER_ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR2(200) NOT NULL,
    USER_ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT NX_USERS_ROLE_CHK CHECK (USER_ROLE IN ('USER','ADMIN'))
);

CREATE TABLE NX_TECHNICIANS (
    TECH_ID NUMBER PRIMARY KEY,
    TECH_NAME VARCHAR2(100) NOT NULL,
    SPECIALIZATION VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150),
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT NX_TECH_ACTIVE_CHK CHECK (ACTIVE IN (0,1))
);

CREATE TABLE NX_TICKETS (
    TICKET_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(2000) NOT NULL,
    CATEGORY VARCHAR2(50) NOT NULL,
    PRIORITY VARCHAR2(20) DEFAULT 'MEDIUM' NOT NULL,
    STATUS VARCHAR2(30) DEFAULT 'OPEN' NOT NULL,
    CREATED_BY NUMBER NOT NULL,
    ASSIGNED_TO NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT NX_TICKET_USER_FK FOREIGN KEY (CREATED_BY) REFERENCES NX_USERS(USER_ID),
    CONSTRAINT NX_TICKET_TECH_FK FOREIGN KEY (ASSIGNED_TO) REFERENCES NX_TECHNICIANS(TECH_ID),
    CONSTRAINT NX_TICKET_PRIORITY_CHK CHECK (PRIORITY IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    CONSTRAINT NX_TICKET_STATUS_CHK CHECK (STATUS IN ('OPEN','ASSIGNED','IN_PROGRESS','RESOLVED','CLOSED'))
);

CREATE TABLE NX_TICKET_COMMENTS (
    COMMENT_ID NUMBER PRIMARY KEY,
    TICKET_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    COMMENT_TEXT VARCHAR2(2000) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT NX_COMMENT_TICKET_FK FOREIGN KEY (TICKET_ID)
        REFERENCES NX_TICKETS(TICKET_ID) ON DELETE CASCADE,
    CONSTRAINT NX_COMMENT_USER_FK FOREIGN KEY (USER_ID)
        REFERENCES NX_USERS(USER_ID)
);

CREATE SEQUENCE NX_USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NX_TECH_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NX_TICKET_SEQ START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NX_COMMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

INSERT INTO NX_USERS (USER_ID,FULL_NAME,EMAIL,USER_PASSWORD,USER_ROLE)
VALUES (NX_USER_SEQ.NEXTVAL,'System Administrator','admin@nexdesk.com','admin123','ADMIN');

INSERT INTO NX_USERS (USER_ID,FULL_NAME,EMAIL,USER_PASSWORD,USER_ROLE)
VALUES (NX_USER_SEQ.NEXTVAL,'Demo User','demo@nexdesk.com','demo123','USER');

INSERT INTO NX_TECHNICIANS (TECH_ID,TECH_NAME,SPECIALIZATION,EMAIL)
VALUES (NX_TECH_SEQ.NEXTVAL,'Aarav Sharma','Hardware','aarav@nexdesk.com');

INSERT INTO NX_TECHNICIANS (TECH_ID,TECH_NAME,SPECIALIZATION,EMAIL)
VALUES (NX_TECH_SEQ.NEXTVAL,'Meera Patil','Network','meera@nexdesk.com');

INSERT INTO NX_TECHNICIANS (TECH_ID,TECH_NAME,SPECIALIZATION,EMAIL)
VALUES (NX_TECH_SEQ.NEXTVAL,'Kabir Joshi','Software','kabir@nexdesk.com');

INSERT INTO NX_TICKETS
(TICKET_ID,TITLE,DESCRIPTION,CATEGORY,PRIORITY,STATUS,CREATED_BY)
SELECT NX_TICKET_SEQ.NEXTVAL,
       'Laptop not powering on',
       'The office laptop does not start when the power button is pressed.',
       'Hardware','HIGH','OPEN',USER_ID
FROM NX_USERS
WHERE EMAIL='demo@nexdesk.com';

COMMIT;

SELECT USER_ID,FULL_NAME,EMAIL,USER_ROLE FROM NX_USERS ORDER BY USER_ID;
SELECT TECH_ID,TECH_NAME,SPECIALIZATION,EMAIL,ACTIVE FROM NX_TECHNICIANS ORDER BY TECH_ID;
SELECT TICKET_ID,TITLE,CATEGORY,PRIORITY,STATUS,CREATED_BY,ASSIGNED_TO
FROM NX_TICKETS ORDER BY TICKET_ID DESC;
