let currentUser=null,currentTickets=[],technicians=[];
const $=id=>document.getElementById(id),enc=x=>encodeURIComponent(x??"");
async function api(path,params={},method="GET"){let q=Object.entries(params).map(([k,v])=>enc(k)+"="+enc(v)).join("&");let r=await fetch(path+(q?"?"+q:""),{method});let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
function toast(s){let x=document.createElement("div");x.className="toast";x.textContent=s;$("toast").appendChild(x);setTimeout(()=>x.remove(),2500)}
$("switchAuth").onclick=()=>{let s=$("signupForm").classList.toggle("hidden");$("loginForm").classList.toggle("hidden");$("authTitle").textContent=s?"Create your account.":"Welcome back."; $("authText").textContent=s?"Join NexDesk and keep your IT requests in one place.":"Sign in to manage incidents, requests and IT support from one place."; $("switchText").textContent=s?"Already have an account?":"New to NexDesk?";$("switchAuth").textContent=s?"Sign in":"Create an account"};
$("loginForm").onsubmit=async e=>{e.preventDefault();try{currentUser=await api("/api/login",{email:$("loginEmail").value,password:$("loginPassword").value},"POST");enter()}catch(x){toast(x.message)}};
$("signupForm").onsubmit=async e=>{e.preventDefault();try{currentUser=await api("/api/signup",{name:$("signupName").value,email:$("signupEmail").value,password:$("signupPassword").value},"POST");toast("Account created.");enter()}catch(x){toast(x.message)}};
$("logout").onclick=()=>{currentUser=null;$("appView").classList.add("hidden");$("authView").classList.remove("hidden")};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function enter(){$("authView").classList.add("hidden");$("appView").classList.remove("hidden");$("sideName").textContent=currentUser.name;$("sideRole").textContent=currentUser.role;$("avatar").textContent=currentUser.name[0].toUpperCase();$("topAvatar").textContent=currentUser.name[0].toUpperCase();document.querySelectorAll(".adminOnly").forEach(x=>x.classList.toggle("hidden",currentUser.role!=="ADMIN"));showPage("overview");loadTickets()}
function showPage(p){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$("page-"+p).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("pageTitle").textContent=p==="create"?"New Request":p==="admin"?"Admin Console":p==="tickets"?"My Tickets":"Overview";if(p==="admin"&&currentUser.role==="ADMIN")loadAdmin()}
async function loadTickets(){try{currentTickets=await api("/api/tickets",currentUser.role==="ADMIN"?{}:{userId:currentUser.id});renderStats();renderRecent();renderTickets()}catch(x){toast(x.message)}}
function renderStats(){let n=s=>currentTickets.filter(t=>t.status===s).length;$("statOpen").textContent=n("OPEN")+n("ASSIGNED");$("statProgress").textContent=n("IN_PROGRESS");$("statResolved").textContent=n("RESOLVED")+n("CLOSED");$("statTotal").textContent=currentTickets.length;$("hello").textContent="Good day, "+currentUser.name.split(" ")[0]+"."}
function card(t){return `<div class="ticket" onclick="openTicket(${t.id})"><div><h4><span style="color:#a0a9b5;font-size:9px">#${t.id}</span> ${esc(t.title)}</h4><p>${esc(t.category)} · ${esc(t.creatorName)} · ${date(t.createdAt)}${t.technicianName?" · "+esc(t.technicianName):""}</p></div><div class="ticket-meta"><span class="pill priority-${t.priority}">${t.priority}</span><span class="pill status-${t.status}">${t.status.replace("_"," ")}</span></div></div>`}
function renderRecent(){$("recentList").innerHTML=currentTickets.slice(0,5).map(card).join("")||empty("No requests yet. Create your first support request.")}
function renderTickets(){let s=($("searchBox").value||"").toLowerCase(),f=$("statusFilter").value||"";let x=currentTickets.filter(t=>(!f||t.status===f)&&(!s||`${t.id} ${t.title} ${t.category}`.toLowerCase().includes(s)));$("allList").innerHTML=x.map(card).join("")||empty("No matching tickets found.")}
$("searchBox").oninput=renderTickets;$("statusFilter").onchange=renderTickets;
$("ticketForm").onsubmit=async e=>{e.preventDefault();try{let x=await api("/api/tickets",{userId:currentUser.id,title:$("ticketTitle").value,description:$("ticketDescription").value,category:$("ticketCategory").value,priority:$("ticketPriority").value},"POST");toast("Request #"+x.ticketId+" created.");e.target.reset();$("ticketPriority").value="MEDIUM";showPage("tickets");loadTickets()}catch(x){toast(x.message)}};
async function loadAdmin(){try{let all=await api("/api/tickets");technicians=await api("/api/technicians");$("adminList").innerHTML=all.map(adminCard).join("")||empty("No tickets.");$("techList").innerHTML=technicians.map(t=>`<div class="tech"><b>${esc(t.name)}</b><small>${esc(t.specialization)} · ${esc(t.email)}</small></div>`).join("")}catch(x){toast(x.message)}}
function adminCard(t){let o=technicians.map(x=>`<option value="${x.id}" ${t.assignedTo==x.id?"selected":""}>${esc(x.name)}</option>`).join("");return `<div class="ticket"><div style="width:100%"><h4>#${t.id} ${esc(t.title)}</h4><p>${esc(t.creatorName)} · ${t.status} · ${t.priority}</p><div class="admin-controls" onclick="event.stopPropagation()"><select id="tech-${t.id}"><option value="">Assign technician</option>${o}</select><button class="primary" onclick="assign(${t.id})">Assign</button><select id="status-${t.id}"><option ${t.status==="OPEN"?"selected":""}>OPEN</option><option ${t.status==="ASSIGNED"?"selected":""}>ASSIGNED</option><option ${t.status==="IN_PROGRESS"?"selected":""}>IN_PROGRESS</option><option ${t.status==="RESOLVED"?"selected":""}>RESOLVED</option><option ${t.status==="CLOSED"?"selected":""}>CLOSED</option></select><button class="primary" onclick="updateStatus(${t.id})">Update</button></div></div><div class="ticket-meta"><span class="pill priority-${t.priority}">${t.priority}</span></div></div>`}
async function assign(id){let v=$("tech-"+id).value;if(!v){toast("Select a technician.");return}try{await api("/api/assign",{ticketId:id,techId:v},"POST");toast("Ticket assigned.");loadAdmin();loadTickets()}catch(x){toast(x.message)}}
async function updateStatus(id){try{await api("/api/status",{ticketId:id,status:$("status-"+id).value},"POST");toast("Status updated.");loadAdmin();loadTickets()}catch(x){toast(x.message)}}
async function openTicket(id){try{let t=await api("/api/ticket",{id});$("modalBody").innerHTML=`<div class="detail"><span class="eyebrow">TICKET #${t.id}</span><h2>${esc(t.title)}</h2><div class="ticket-meta"><span class="pill priority-${t.priority}">${t.priority}</span><span class="pill status-${t.status}">${t.status}</span></div><p class="desc">${esc(t.description)}</p><div class="detail-row"><div class="detail-box"><small>CATEGORY</small><b>${esc(t.category)}</b></div><div class="detail-box"><small>REQUESTER</small><b>${esc(t.creatorName)}</b></div><div class="detail-box"><small>TECHNICIAN</small><b>${esc(t.technicianName||"Unassigned")}</b></div><div class="detail-box"><small>CREATED</small><b>${date(t.createdAt)}</b></div></div></div>`;$("ticketModal").classList.remove("hidden")}catch(x){toast(x.message)}}
function closeModal(){$("ticketModal").classList.add("hidden")}$("ticketModal").onclick=e=>{if(e.target.id==="ticketModal")closeModal()};
function date(x){return x?new Date(x.replace(" ","T")).toLocaleString([],{dateStyle:"medium",timeStyle:"short"}):"—"}function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function empty(x){return `<div style="background:#fff;border:1px dashed #d9e0e8;border-radius:11px;padding:24px;text-align:center;color:#8b96a5;font-size:11px">${x}</div>`}
